"""Add new herb fields

Revision ID: fc6de55247f7
Revises: 
Create Date: 2025-04-17 12:07:48.937586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6de55247f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('english_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('photo_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usage_parts', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herb', schema=None) as batch_op:
        batch_op.drop_column('usage_parts')
        batch_op.drop_column('page_number')
        batch_op.drop_column('photo_number')
        batch_op.drop_column('english_name')

    # ### end Alembic commands ###
